ALTER USER 'root'@'localhost' IDENTIFIED BY 'asd123';
CREATE USER 'myUser'@'172.17.0.1' IDENTIFIED WITH mysql_native_password BY 'asd123';
GRANT ALL PRIVILEGES ON *.* TO 'myUser'@'172.17.0.1';
CREATE DATABASE test_db;
USE test_db;
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(255) DEFAULT "guest",
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255),
  createdAt TIMESTAMP,
  updatedAt TIMESTAMP
);